# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/reece/Misc/GameEngine/Master/Public/DirectXTex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/reece/Misc/GameEngine/Master/Public/DirectXTex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/reece/Misc/GameEngine/Master/Public/DirectXTex/CMakeFiles /run/media/reece/Misc/GameEngine/Master/Public/DirectXTex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/reece/Misc/GameEngine/Master/Public/DirectXTex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named texdiag

# Build rule for target.
texdiag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 texdiag
.PHONY : texdiag

# fast build rule for target.
texdiag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texdiag.dir/build.make CMakeFiles/texdiag.dir/build
.PHONY : texdiag/fast

#=============================================================================
# Target rules for targets named texconv

# Build rule for target.
texconv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 texconv
.PHONY : texconv

# fast build rule for target.
texconv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/build
.PHONY : texconv/fast

#=============================================================================
# Target rules for targets named texassemble

# Build rule for target.
texassemble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 texassemble
.PHONY : texassemble

# fast build rule for target.
texassemble/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/build
.PHONY : texassemble/fast

#=============================================================================
# Target rules for targets named DirectXTex

# Build rule for target.
DirectXTex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DirectXTex
.PHONY : DirectXTex

# fast build rule for target.
DirectXTex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/build
.PHONY : DirectXTex/fast

DirectXTex/BC.o: DirectXTex/BC.cpp.o

.PHONY : DirectXTex/BC.o

# target to build an object file
DirectXTex/BC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC.cpp.o
.PHONY : DirectXTex/BC.cpp.o

DirectXTex/BC.i: DirectXTex/BC.cpp.i

.PHONY : DirectXTex/BC.i

# target to preprocess a source file
DirectXTex/BC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC.cpp.i
.PHONY : DirectXTex/BC.cpp.i

DirectXTex/BC.s: DirectXTex/BC.cpp.s

.PHONY : DirectXTex/BC.s

# target to generate assembly for a file
DirectXTex/BC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC.cpp.s
.PHONY : DirectXTex/BC.cpp.s

DirectXTex/BC4BC5.o: DirectXTex/BC4BC5.cpp.o

.PHONY : DirectXTex/BC4BC5.o

# target to build an object file
DirectXTex/BC4BC5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC4BC5.cpp.o
.PHONY : DirectXTex/BC4BC5.cpp.o

DirectXTex/BC4BC5.i: DirectXTex/BC4BC5.cpp.i

.PHONY : DirectXTex/BC4BC5.i

# target to preprocess a source file
DirectXTex/BC4BC5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC4BC5.cpp.i
.PHONY : DirectXTex/BC4BC5.cpp.i

DirectXTex/BC4BC5.s: DirectXTex/BC4BC5.cpp.s

.PHONY : DirectXTex/BC4BC5.s

# target to generate assembly for a file
DirectXTex/BC4BC5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC4BC5.cpp.s
.PHONY : DirectXTex/BC4BC5.cpp.s

DirectXTex/BC6HBC7.o: DirectXTex/BC6HBC7.cpp.o

.PHONY : DirectXTex/BC6HBC7.o

# target to build an object file
DirectXTex/BC6HBC7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC6HBC7.cpp.o
.PHONY : DirectXTex/BC6HBC7.cpp.o

DirectXTex/BC6HBC7.i: DirectXTex/BC6HBC7.cpp.i

.PHONY : DirectXTex/BC6HBC7.i

# target to preprocess a source file
DirectXTex/BC6HBC7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC6HBC7.cpp.i
.PHONY : DirectXTex/BC6HBC7.cpp.i

DirectXTex/BC6HBC7.s: DirectXTex/BC6HBC7.cpp.s

.PHONY : DirectXTex/BC6HBC7.s

# target to generate assembly for a file
DirectXTex/BC6HBC7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/BC6HBC7.cpp.s
.PHONY : DirectXTex/BC6HBC7.cpp.s

DirectXTex/DirectXTexConvert.o: DirectXTex/DirectXTexConvert.cpp.o

.PHONY : DirectXTex/DirectXTexConvert.o

# target to build an object file
DirectXTex/DirectXTexConvert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexConvert.cpp.o
.PHONY : DirectXTex/DirectXTexConvert.cpp.o

DirectXTex/DirectXTexConvert.i: DirectXTex/DirectXTexConvert.cpp.i

.PHONY : DirectXTex/DirectXTexConvert.i

# target to preprocess a source file
DirectXTex/DirectXTexConvert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexConvert.cpp.i
.PHONY : DirectXTex/DirectXTexConvert.cpp.i

DirectXTex/DirectXTexConvert.s: DirectXTex/DirectXTexConvert.cpp.s

.PHONY : DirectXTex/DirectXTexConvert.s

# target to generate assembly for a file
DirectXTex/DirectXTexConvert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexConvert.cpp.s
.PHONY : DirectXTex/DirectXTexConvert.cpp.s

DirectXTex/DirectXTexD3D11.o: DirectXTex/DirectXTexD3D11.cpp.o

.PHONY : DirectXTex/DirectXTexD3D11.o

# target to build an object file
DirectXTex/DirectXTexD3D11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D11.cpp.o
.PHONY : DirectXTex/DirectXTexD3D11.cpp.o

DirectXTex/DirectXTexD3D11.i: DirectXTex/DirectXTexD3D11.cpp.i

.PHONY : DirectXTex/DirectXTexD3D11.i

# target to preprocess a source file
DirectXTex/DirectXTexD3D11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D11.cpp.i
.PHONY : DirectXTex/DirectXTexD3D11.cpp.i

DirectXTex/DirectXTexD3D11.s: DirectXTex/DirectXTexD3D11.cpp.s

.PHONY : DirectXTex/DirectXTexD3D11.s

# target to generate assembly for a file
DirectXTex/DirectXTexD3D11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D11.cpp.s
.PHONY : DirectXTex/DirectXTexD3D11.cpp.s

DirectXTex/DirectXTexD3D12.o: DirectXTex/DirectXTexD3D12.cpp.o

.PHONY : DirectXTex/DirectXTexD3D12.o

# target to build an object file
DirectXTex/DirectXTexD3D12.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D12.cpp.o
.PHONY : DirectXTex/DirectXTexD3D12.cpp.o

DirectXTex/DirectXTexD3D12.i: DirectXTex/DirectXTexD3D12.cpp.i

.PHONY : DirectXTex/DirectXTexD3D12.i

# target to preprocess a source file
DirectXTex/DirectXTexD3D12.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D12.cpp.i
.PHONY : DirectXTex/DirectXTexD3D12.cpp.i

DirectXTex/DirectXTexD3D12.s: DirectXTex/DirectXTexD3D12.cpp.s

.PHONY : DirectXTex/DirectXTexD3D12.s

# target to generate assembly for a file
DirectXTex/DirectXTexD3D12.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexD3D12.cpp.s
.PHONY : DirectXTex/DirectXTexD3D12.cpp.s

DirectXTex/DirectXTexDDS.o: DirectXTex/DirectXTexDDS.cpp.o

.PHONY : DirectXTex/DirectXTexDDS.o

# target to build an object file
DirectXTex/DirectXTexDDS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexDDS.cpp.o
.PHONY : DirectXTex/DirectXTexDDS.cpp.o

DirectXTex/DirectXTexDDS.i: DirectXTex/DirectXTexDDS.cpp.i

.PHONY : DirectXTex/DirectXTexDDS.i

# target to preprocess a source file
DirectXTex/DirectXTexDDS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexDDS.cpp.i
.PHONY : DirectXTex/DirectXTexDDS.cpp.i

DirectXTex/DirectXTexDDS.s: DirectXTex/DirectXTexDDS.cpp.s

.PHONY : DirectXTex/DirectXTexDDS.s

# target to generate assembly for a file
DirectXTex/DirectXTexDDS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexDDS.cpp.s
.PHONY : DirectXTex/DirectXTexDDS.cpp.s

DirectXTex/DirectXTexFlipRotate.o: DirectXTex/DirectXTexFlipRotate.cpp.o

.PHONY : DirectXTex/DirectXTexFlipRotate.o

# target to build an object file
DirectXTex/DirectXTexFlipRotate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexFlipRotate.cpp.o
.PHONY : DirectXTex/DirectXTexFlipRotate.cpp.o

DirectXTex/DirectXTexFlipRotate.i: DirectXTex/DirectXTexFlipRotate.cpp.i

.PHONY : DirectXTex/DirectXTexFlipRotate.i

# target to preprocess a source file
DirectXTex/DirectXTexFlipRotate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexFlipRotate.cpp.i
.PHONY : DirectXTex/DirectXTexFlipRotate.cpp.i

DirectXTex/DirectXTexFlipRotate.s: DirectXTex/DirectXTexFlipRotate.cpp.s

.PHONY : DirectXTex/DirectXTexFlipRotate.s

# target to generate assembly for a file
DirectXTex/DirectXTexFlipRotate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexFlipRotate.cpp.s
.PHONY : DirectXTex/DirectXTexFlipRotate.cpp.s

DirectXTex/DirectXTexHDR.o: DirectXTex/DirectXTexHDR.cpp.o

.PHONY : DirectXTex/DirectXTexHDR.o

# target to build an object file
DirectXTex/DirectXTexHDR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexHDR.cpp.o
.PHONY : DirectXTex/DirectXTexHDR.cpp.o

DirectXTex/DirectXTexHDR.i: DirectXTex/DirectXTexHDR.cpp.i

.PHONY : DirectXTex/DirectXTexHDR.i

# target to preprocess a source file
DirectXTex/DirectXTexHDR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexHDR.cpp.i
.PHONY : DirectXTex/DirectXTexHDR.cpp.i

DirectXTex/DirectXTexHDR.s: DirectXTex/DirectXTexHDR.cpp.s

.PHONY : DirectXTex/DirectXTexHDR.s

# target to generate assembly for a file
DirectXTex/DirectXTexHDR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexHDR.cpp.s
.PHONY : DirectXTex/DirectXTexHDR.cpp.s

DirectXTex/DirectXTexImage.o: DirectXTex/DirectXTexImage.cpp.o

.PHONY : DirectXTex/DirectXTexImage.o

# target to build an object file
DirectXTex/DirectXTexImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexImage.cpp.o
.PHONY : DirectXTex/DirectXTexImage.cpp.o

DirectXTex/DirectXTexImage.i: DirectXTex/DirectXTexImage.cpp.i

.PHONY : DirectXTex/DirectXTexImage.i

# target to preprocess a source file
DirectXTex/DirectXTexImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexImage.cpp.i
.PHONY : DirectXTex/DirectXTexImage.cpp.i

DirectXTex/DirectXTexImage.s: DirectXTex/DirectXTexImage.cpp.s

.PHONY : DirectXTex/DirectXTexImage.s

# target to generate assembly for a file
DirectXTex/DirectXTexImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexImage.cpp.s
.PHONY : DirectXTex/DirectXTexImage.cpp.s

DirectXTex/DirectXTexMipmaps.o: DirectXTex/DirectXTexMipmaps.cpp.o

.PHONY : DirectXTex/DirectXTexMipmaps.o

# target to build an object file
DirectXTex/DirectXTexMipmaps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMipmaps.cpp.o
.PHONY : DirectXTex/DirectXTexMipmaps.cpp.o

DirectXTex/DirectXTexMipmaps.i: DirectXTex/DirectXTexMipmaps.cpp.i

.PHONY : DirectXTex/DirectXTexMipmaps.i

# target to preprocess a source file
DirectXTex/DirectXTexMipmaps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMipmaps.cpp.i
.PHONY : DirectXTex/DirectXTexMipmaps.cpp.i

DirectXTex/DirectXTexMipmaps.s: DirectXTex/DirectXTexMipmaps.cpp.s

.PHONY : DirectXTex/DirectXTexMipmaps.s

# target to generate assembly for a file
DirectXTex/DirectXTexMipmaps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMipmaps.cpp.s
.PHONY : DirectXTex/DirectXTexMipmaps.cpp.s

DirectXTex/DirectXTexMisc.o: DirectXTex/DirectXTexMisc.cpp.o

.PHONY : DirectXTex/DirectXTexMisc.o

# target to build an object file
DirectXTex/DirectXTexMisc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMisc.cpp.o
.PHONY : DirectXTex/DirectXTexMisc.cpp.o

DirectXTex/DirectXTexMisc.i: DirectXTex/DirectXTexMisc.cpp.i

.PHONY : DirectXTex/DirectXTexMisc.i

# target to preprocess a source file
DirectXTex/DirectXTexMisc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMisc.cpp.i
.PHONY : DirectXTex/DirectXTexMisc.cpp.i

DirectXTex/DirectXTexMisc.s: DirectXTex/DirectXTexMisc.cpp.s

.PHONY : DirectXTex/DirectXTexMisc.s

# target to generate assembly for a file
DirectXTex/DirectXTexMisc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexMisc.cpp.s
.PHONY : DirectXTex/DirectXTexMisc.cpp.s

DirectXTex/DirectXTexNormalMaps.o: DirectXTex/DirectXTexNormalMaps.cpp.o

.PHONY : DirectXTex/DirectXTexNormalMaps.o

# target to build an object file
DirectXTex/DirectXTexNormalMaps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexNormalMaps.cpp.o
.PHONY : DirectXTex/DirectXTexNormalMaps.cpp.o

DirectXTex/DirectXTexNormalMaps.i: DirectXTex/DirectXTexNormalMaps.cpp.i

.PHONY : DirectXTex/DirectXTexNormalMaps.i

# target to preprocess a source file
DirectXTex/DirectXTexNormalMaps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexNormalMaps.cpp.i
.PHONY : DirectXTex/DirectXTexNormalMaps.cpp.i

DirectXTex/DirectXTexNormalMaps.s: DirectXTex/DirectXTexNormalMaps.cpp.s

.PHONY : DirectXTex/DirectXTexNormalMaps.s

# target to generate assembly for a file
DirectXTex/DirectXTexNormalMaps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexNormalMaps.cpp.s
.PHONY : DirectXTex/DirectXTexNormalMaps.cpp.s

DirectXTex/DirectXTexPMAlpha.o: DirectXTex/DirectXTexPMAlpha.cpp.o

.PHONY : DirectXTex/DirectXTexPMAlpha.o

# target to build an object file
DirectXTex/DirectXTexPMAlpha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexPMAlpha.cpp.o
.PHONY : DirectXTex/DirectXTexPMAlpha.cpp.o

DirectXTex/DirectXTexPMAlpha.i: DirectXTex/DirectXTexPMAlpha.cpp.i

.PHONY : DirectXTex/DirectXTexPMAlpha.i

# target to preprocess a source file
DirectXTex/DirectXTexPMAlpha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexPMAlpha.cpp.i
.PHONY : DirectXTex/DirectXTexPMAlpha.cpp.i

DirectXTex/DirectXTexPMAlpha.s: DirectXTex/DirectXTexPMAlpha.cpp.s

.PHONY : DirectXTex/DirectXTexPMAlpha.s

# target to generate assembly for a file
DirectXTex/DirectXTexPMAlpha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexPMAlpha.cpp.s
.PHONY : DirectXTex/DirectXTexPMAlpha.cpp.s

DirectXTex/DirectXTexResize.o: DirectXTex/DirectXTexResize.cpp.o

.PHONY : DirectXTex/DirectXTexResize.o

# target to build an object file
DirectXTex/DirectXTexResize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexResize.cpp.o
.PHONY : DirectXTex/DirectXTexResize.cpp.o

DirectXTex/DirectXTexResize.i: DirectXTex/DirectXTexResize.cpp.i

.PHONY : DirectXTex/DirectXTexResize.i

# target to preprocess a source file
DirectXTex/DirectXTexResize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexResize.cpp.i
.PHONY : DirectXTex/DirectXTexResize.cpp.i

DirectXTex/DirectXTexResize.s: DirectXTex/DirectXTexResize.cpp.s

.PHONY : DirectXTex/DirectXTexResize.s

# target to generate assembly for a file
DirectXTex/DirectXTexResize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexResize.cpp.s
.PHONY : DirectXTex/DirectXTexResize.cpp.s

DirectXTex/DirectXTexTGA.o: DirectXTex/DirectXTexTGA.cpp.o

.PHONY : DirectXTex/DirectXTexTGA.o

# target to build an object file
DirectXTex/DirectXTexTGA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexTGA.cpp.o
.PHONY : DirectXTex/DirectXTexTGA.cpp.o

DirectXTex/DirectXTexTGA.i: DirectXTex/DirectXTexTGA.cpp.i

.PHONY : DirectXTex/DirectXTexTGA.i

# target to preprocess a source file
DirectXTex/DirectXTexTGA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexTGA.cpp.i
.PHONY : DirectXTex/DirectXTexTGA.cpp.i

DirectXTex/DirectXTexTGA.s: DirectXTex/DirectXTexTGA.cpp.s

.PHONY : DirectXTex/DirectXTexTGA.s

# target to generate assembly for a file
DirectXTex/DirectXTexTGA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexTGA.cpp.s
.PHONY : DirectXTex/DirectXTexTGA.cpp.s

DirectXTex/DirectXTexUtil.o: DirectXTex/DirectXTexUtil.cpp.o

.PHONY : DirectXTex/DirectXTexUtil.o

# target to build an object file
DirectXTex/DirectXTexUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexUtil.cpp.o
.PHONY : DirectXTex/DirectXTexUtil.cpp.o

DirectXTex/DirectXTexUtil.i: DirectXTex/DirectXTexUtil.cpp.i

.PHONY : DirectXTex/DirectXTexUtil.i

# target to preprocess a source file
DirectXTex/DirectXTexUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexUtil.cpp.i
.PHONY : DirectXTex/DirectXTexUtil.cpp.i

DirectXTex/DirectXTexUtil.s: DirectXTex/DirectXTexUtil.cpp.s

.PHONY : DirectXTex/DirectXTexUtil.s

# target to generate assembly for a file
DirectXTex/DirectXTexUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/DirectXTex/DirectXTexUtil.cpp.s
.PHONY : DirectXTex/DirectXTexUtil.cpp.s

Texassemble/AnimatedGif.o: Texassemble/AnimatedGif.cpp.o

.PHONY : Texassemble/AnimatedGif.o

# target to build an object file
Texassemble/AnimatedGif.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/AnimatedGif.cpp.o
.PHONY : Texassemble/AnimatedGif.cpp.o

Texassemble/AnimatedGif.i: Texassemble/AnimatedGif.cpp.i

.PHONY : Texassemble/AnimatedGif.i

# target to preprocess a source file
Texassemble/AnimatedGif.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/AnimatedGif.cpp.i
.PHONY : Texassemble/AnimatedGif.cpp.i

Texassemble/AnimatedGif.s: Texassemble/AnimatedGif.cpp.s

.PHONY : Texassemble/AnimatedGif.s

# target to generate assembly for a file
Texassemble/AnimatedGif.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/AnimatedGif.cpp.s
.PHONY : Texassemble/AnimatedGif.cpp.s

Texassemble/texassemble.o: Texassemble/texassemble.cpp.o

.PHONY : Texassemble/texassemble.o

# target to build an object file
Texassemble/texassemble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/texassemble.cpp.o
.PHONY : Texassemble/texassemble.cpp.o

Texassemble/texassemble.i: Texassemble/texassemble.cpp.i

.PHONY : Texassemble/texassemble.i

# target to preprocess a source file
Texassemble/texassemble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/texassemble.cpp.i
.PHONY : Texassemble/texassemble.cpp.i

Texassemble/texassemble.s: Texassemble/texassemble.cpp.s

.PHONY : Texassemble/texassemble.s

# target to generate assembly for a file
Texassemble/texassemble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texassemble.dir/build.make CMakeFiles/texassemble.dir/Texassemble/texassemble.cpp.s
.PHONY : Texassemble/texassemble.cpp.s

Texconv/ExtendedBMP.o: Texconv/ExtendedBMP.cpp.o

.PHONY : Texconv/ExtendedBMP.o

# target to build an object file
Texconv/ExtendedBMP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/ExtendedBMP.cpp.o
.PHONY : Texconv/ExtendedBMP.cpp.o

Texconv/ExtendedBMP.i: Texconv/ExtendedBMP.cpp.i

.PHONY : Texconv/ExtendedBMP.i

# target to preprocess a source file
Texconv/ExtendedBMP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/ExtendedBMP.cpp.i
.PHONY : Texconv/ExtendedBMP.cpp.i

Texconv/ExtendedBMP.s: Texconv/ExtendedBMP.cpp.s

.PHONY : Texconv/ExtendedBMP.s

# target to generate assembly for a file
Texconv/ExtendedBMP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/ExtendedBMP.cpp.s
.PHONY : Texconv/ExtendedBMP.cpp.s

Texconv/PortablePixMap.o: Texconv/PortablePixMap.cpp.o

.PHONY : Texconv/PortablePixMap.o

# target to build an object file
Texconv/PortablePixMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/PortablePixMap.cpp.o
.PHONY : Texconv/PortablePixMap.cpp.o

Texconv/PortablePixMap.i: Texconv/PortablePixMap.cpp.i

.PHONY : Texconv/PortablePixMap.i

# target to preprocess a source file
Texconv/PortablePixMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/PortablePixMap.cpp.i
.PHONY : Texconv/PortablePixMap.cpp.i

Texconv/PortablePixMap.s: Texconv/PortablePixMap.cpp.s

.PHONY : Texconv/PortablePixMap.s

# target to generate assembly for a file
Texconv/PortablePixMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/PortablePixMap.cpp.s
.PHONY : Texconv/PortablePixMap.cpp.s

Texconv/texconv.o: Texconv/texconv.cpp.o

.PHONY : Texconv/texconv.o

# target to build an object file
Texconv/texconv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/texconv.cpp.o
.PHONY : Texconv/texconv.cpp.o

Texconv/texconv.i: Texconv/texconv.cpp.i

.PHONY : Texconv/texconv.i

# target to preprocess a source file
Texconv/texconv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/texconv.cpp.i
.PHONY : Texconv/texconv.cpp.i

Texconv/texconv.s: Texconv/texconv.cpp.s

.PHONY : Texconv/texconv.s

# target to generate assembly for a file
Texconv/texconv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texconv.dir/build.make CMakeFiles/texconv.dir/Texconv/texconv.cpp.s
.PHONY : Texconv/texconv.cpp.s

Texdiag/texdiag.o: Texdiag/texdiag.cpp.o

.PHONY : Texdiag/texdiag.o

# target to build an object file
Texdiag/texdiag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texdiag.dir/build.make CMakeFiles/texdiag.dir/Texdiag/texdiag.cpp.o
.PHONY : Texdiag/texdiag.cpp.o

Texdiag/texdiag.i: Texdiag/texdiag.cpp.i

.PHONY : Texdiag/texdiag.i

# target to preprocess a source file
Texdiag/texdiag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texdiag.dir/build.make CMakeFiles/texdiag.dir/Texdiag/texdiag.cpp.i
.PHONY : Texdiag/texdiag.cpp.i

Texdiag/texdiag.s: Texdiag/texdiag.cpp.s

.PHONY : Texdiag/texdiag.s

# target to generate assembly for a file
Texdiag/texdiag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texdiag.dir/build.make CMakeFiles/texdiag.dir/Texdiag/texdiag.cpp.s
.PHONY : Texdiag/texdiag.cpp.s

# target to build an object file
cmake_pch.hxx.pch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/cmake_pch.hxx.pch
.PHONY : cmake_pch.hxx.pch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DirectXTex.dir/build.make CMakeFiles/DirectXTex.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DirectXTex"
	@echo "... texassemble"
	@echo "... texconv"
	@echo "... texdiag"
	@echo "... DirectXTex/BC.o"
	@echo "... DirectXTex/BC.i"
	@echo "... DirectXTex/BC.s"
	@echo "... DirectXTex/BC4BC5.o"
	@echo "... DirectXTex/BC4BC5.i"
	@echo "... DirectXTex/BC4BC5.s"
	@echo "... DirectXTex/BC6HBC7.o"
	@echo "... DirectXTex/BC6HBC7.i"
	@echo "... DirectXTex/BC6HBC7.s"
	@echo "... DirectXTex/DirectXTexConvert.o"
	@echo "... DirectXTex/DirectXTexConvert.i"
	@echo "... DirectXTex/DirectXTexConvert.s"
	@echo "... DirectXTex/DirectXTexD3D11.o"
	@echo "... DirectXTex/DirectXTexD3D11.i"
	@echo "... DirectXTex/DirectXTexD3D11.s"
	@echo "... DirectXTex/DirectXTexD3D12.o"
	@echo "... DirectXTex/DirectXTexD3D12.i"
	@echo "... DirectXTex/DirectXTexD3D12.s"
	@echo "... DirectXTex/DirectXTexDDS.o"
	@echo "... DirectXTex/DirectXTexDDS.i"
	@echo "... DirectXTex/DirectXTexDDS.s"
	@echo "... DirectXTex/DirectXTexFlipRotate.o"
	@echo "... DirectXTex/DirectXTexFlipRotate.i"
	@echo "... DirectXTex/DirectXTexFlipRotate.s"
	@echo "... DirectXTex/DirectXTexHDR.o"
	@echo "... DirectXTex/DirectXTexHDR.i"
	@echo "... DirectXTex/DirectXTexHDR.s"
	@echo "... DirectXTex/DirectXTexImage.o"
	@echo "... DirectXTex/DirectXTexImage.i"
	@echo "... DirectXTex/DirectXTexImage.s"
	@echo "... DirectXTex/DirectXTexMipmaps.o"
	@echo "... DirectXTex/DirectXTexMipmaps.i"
	@echo "... DirectXTex/DirectXTexMipmaps.s"
	@echo "... DirectXTex/DirectXTexMisc.o"
	@echo "... DirectXTex/DirectXTexMisc.i"
	@echo "... DirectXTex/DirectXTexMisc.s"
	@echo "... DirectXTex/DirectXTexNormalMaps.o"
	@echo "... DirectXTex/DirectXTexNormalMaps.i"
	@echo "... DirectXTex/DirectXTexNormalMaps.s"
	@echo "... DirectXTex/DirectXTexPMAlpha.o"
	@echo "... DirectXTex/DirectXTexPMAlpha.i"
	@echo "... DirectXTex/DirectXTexPMAlpha.s"
	@echo "... DirectXTex/DirectXTexResize.o"
	@echo "... DirectXTex/DirectXTexResize.i"
	@echo "... DirectXTex/DirectXTexResize.s"
	@echo "... DirectXTex/DirectXTexTGA.o"
	@echo "... DirectXTex/DirectXTexTGA.i"
	@echo "... DirectXTex/DirectXTexTGA.s"
	@echo "... DirectXTex/DirectXTexUtil.o"
	@echo "... DirectXTex/DirectXTexUtil.i"
	@echo "... DirectXTex/DirectXTexUtil.s"
	@echo "... Texassemble/AnimatedGif.o"
	@echo "... Texassemble/AnimatedGif.i"
	@echo "... Texassemble/AnimatedGif.s"
	@echo "... Texassemble/texassemble.o"
	@echo "... Texassemble/texassemble.i"
	@echo "... Texassemble/texassemble.s"
	@echo "... Texconv/ExtendedBMP.o"
	@echo "... Texconv/ExtendedBMP.i"
	@echo "... Texconv/ExtendedBMP.s"
	@echo "... Texconv/PortablePixMap.o"
	@echo "... Texconv/PortablePixMap.i"
	@echo "... Texconv/PortablePixMap.s"
	@echo "... Texconv/texconv.o"
	@echo "... Texconv/texconv.i"
	@echo "... Texconv/texconv.s"
	@echo "... Texdiag/texdiag.o"
	@echo "... Texdiag/texdiag.i"
	@echo "... Texdiag/texdiag.s"
	@echo "... cmake_pch.hxx.pch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

